name: Deploy from Self-hosted Runner

on:
  push:
    branches: [main]

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Clear git index cache
        run: |
          git rm --cached -r .
          
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Copy dist to Nginx root
        run: |
          sudo rm -rf /home/ubuntu/MoleLaw_Frontend/dist/*
          sudo cp -r dist/* /home/ubuntu/dist
